### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by jungpaeng** [sudharsan-selvaraj/appium-dashboard-plugin#146]
`appium --use-plugin='appium-dashboard'`

```sh
[Appium] Attempting to load plugin appium-dashboard...
[Appium] Requiring plugin at /Users/been.im/.appium/node_modules/appium-dashboard/lib/index.js
[Appium] AppiumDashboardPlugin has been successfully loaded in 0.693s
[ADB] Found 1 'build-tools' folders under '/Users/been.im/Library/Android/sdk' (newest first):
[ADB]     /Users/been.im/Library/Android/sdk/build-tools/34.0.0
[ADB] Using 'adb' from '/Users/been.im/Library/Android/sdk/platform-tools/adb'
[ADB] Running '/Users/been.im/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
[Appium] Welcome to Appium v2.9.0
[Appium] Non-default server args:
[Appium] {
[Appium]   usePlugins: [
[Appium]     'appium-dashboard'
[Appium]   ]
[Appium] }
[Appium] The autodetected Appium home path: /Users/been.im/.appium
[Appium] Attempting to load driver xcuitest...
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at /Users/been.im/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] XCUITestDriver has been successfully loaded in 0.284s
[Appium] Requiring driver at /Users/been.im/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[Appium] AndroidUiautomator2Driver has been successfully loaded in 0.541s
(node:30809) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[appium-dashboard] Dashboard plugin is enabled and will be served at http://localhost:4723/dashboard
[appium-dashboard] If the appium server is started with different port other than 4723, then use the correct port number to access the device farm dashboard
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.59.118:4723/
[Appium] 	http://100.64.0.1:4723/
[Appium] 	http://169.254.88.185:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@7.17.4 (automationName 'XCUITest')
[Appium]   - uiautomator2@3.5.3 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - device-farm@8.4.7-rc.18
[Appium]   - appium-dashboard@v2.0.3 (ACTIVE)
uncaughtException: SQLITE_READONLY: attempt to write a readonly database
Error:
    at Database.<anonymous> (/Users/been.im/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
    at /Users/been.im/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
    at new Promise (<anonymous>)
    at Query.run (/Users/been.im/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
    at /Users/been.im/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/sequelize.js:650:28
    at SQLiteQueryInterface.bulkUpdate (/Users/been.im/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/abstract/query-interface.js:930:12)
    at Function.update (/Users/been.im/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/model.js:3352:28)
```

**Comment by jungpaeng** [comment]
Not reproduced when running commands with `sudo`

**Comment by halilcifteci** [comment]
You must delete cache and reinstall dashboard plugin.
 /Users/username/.cache
