### ISSUE TITLE
Unable to Load Dashboard with Devices on Windows

### ISSUE THREAD

**Issue by prabhurohith** [sudharsan-selvaraj/appium-dashboard-plugin#54]
**Appium Version** : 2.0.0-beta.25
**OS** : Windows 10
**Node** : v14.17.5

**Logs :** 
[HTTP] --> GET /dashboard/api/sessions?
[HTTP] {}
(node:12668) UnhandledPromiseRejectionWarning: Error:
    at Database.<anonymous> (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\dialects\sqlite\query.js:227:27)
    at C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\dialects\sqlite\query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\dialects\sqlite\query.js:225:12)
    at C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\sequelize.js:642:28
    at SQLiteQueryInterface.rawSelect (C:\
![DashboardIssueSS](https://user-images.githubusercontent.com/26870075/156709504-1dd9fafb-d57a-442a-8bf4-ba37a8b26a7b.PNG)
Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\dialects\abstract\query-interface.js:1021:18)
    at Function.aggregate (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\model.js:2022:19)
    at Function.count (C:\Users\Rohit Prabhu\A
[DashboardIssue.txt](https://github.com/AppiumTestDistribution/appium-device-farm/files/8183417/DashboardIssue.txt)
ppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\model.js:2070:20)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\lib\model.js:2129:27)
(node:12668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[DashboardIssue.txt](https://github.com/sudharsan-selvaraj/appium-dashboard-plugin/files/8185153/DashboardIssue.txt)
![DashboardIssueSS](https://user-images.githubusercontent.com/26870075/156749116-4277342e-c8ba-4c55-bed9-db2b488f5497.PNG)

**Comment by sudharsan-selvaraj** [comment]
From the logs i can see that the dashboard version you are using is `v1.0.0-beta.10`. but the latest version is `v1.0.0-beta.11`. Have you tried updating it to the latest one?

**Comment by prabhurohith** [comment]
in the logs if you could scroll down you can see the updated version used 
[Appium] Available drivers:
[Appium]   - uiautomator2@1.67.0 (automationName 'UiAutomator2')
[Appium]   - espresso@1.45.3 (automationName 'Espresso')
[Appium] Available plugins:
[Appium]   - element-wait@1.0.0-beta.3
[Appium]   - gestures-demo@1.0.0
[Appium]   - device-farm@1.0.0-beta.12 (ACTIVE)
[Appium]   - appium-dashboard@v1.0.0-beta.11 (ACTIVE)
[HTTP] --> GET /dashboard/api/sessions?
[HTTP] {}
(node:13540) UnhandledPromiseRejectionWarning: Error:
    at Database.<anonymous> (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\dialects\sqlite\query.js:227:27)
    at C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\dialects\sqlite\query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\dialects\sqlite\query.js:225:12)
    at C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\sequelize.js:643:28
    at SQLiteQueryInterface.rawSelect (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\dialects\abstract\query-interface.js:1021:18)
    at Function.aggregate (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\model.js:2024:19)
    at Function.count (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\model.js:2072:20)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\Users\Rohit Prabhu\AppData\Roaming\npm\appium-dashboard\node_modules\sequelize\src\model.js:2131:27)
(node:13540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[HTTP] --> GET /dashboard/api/sessions?

**Comment by sudharsan-selvaraj** [comment]
@prabhurohith , at the moment I don't have access for any windows system from my end to reproduce the issue. If possible let's pair up sometime and debug the issue.
