### ISSUE TITLE
SQLITE_ERROR while starting appium server with plugin on macOS

### ISSUE THREAD

**Issue by Kavya341** [sudharsan-selvaraj/appium-dashboard-plugin#65]
Below error is being displayed while trying to start appium server with the plugin on macOS

- [ ] [Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.0.7 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - appium-dashboard@v1.0.0-beta.12 (ACTIVE)
uncaughtException: SQLITE_ERROR: no such column: is_paused
Error:
    at Database.<anonymous> (/Users/kavyat/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/query.js:227:27)
    at /Users/kavyat/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (/Users/kavyat/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/query.js:225:12)
    at /Users/kavyat/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/sequelize.js:643:28
    at SQLiteQueryInterface.bulkUpdate (/Users/kavyat/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/abstract/query-interface.js:908:12)
    at Function.update (/Users/kavyat/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/model.js:3266:28)

**Comment by sudharsan-selvaraj** [comment]
Hi @Kavya341 , Looks like the DB is not synced with the latest changes made to the schema. Can you try the below steps and see if that works.

1. cd `/Users/kavyat/.cache/appium-dashboard-plugin` and delete all the files inside this folder
2. Run `appium plugin uninstall appium-dashboard`
3. Reinstall the plugin `appium plugin install --source=npm appium-dashboard`
4. Start the appium server `appium --use-plugins=appium-dashboard`

**Comment by Kavya341** [comment]
Hey @sudharsan-selvaraj the above solution worked. Thanks

**Comment by sudharsan-selvaraj** [comment]
Sounds great @Kavya341 , I will go ahead and close this issues.
